/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../styles/Home.module.css";
import { data } from "../data";
import { getSession, signIn, signOut } from "next-auth/client";

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
};

export const getStaticProps = () => {
  return {
    props: {
      collectionData: data,
    },
  };
};

export default function Home({ collectionData, session }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-danger">Home</h1>
      {session ? (
        <button className="btn btn-danger" onClick={() => signOut()}>
          Akauntdan chiqish
        </button>
      ) : (
        <button className="btn btn-warning" onClick={() => signIn()}>
          Akauntga kirish
        </button>
      )}
      {session && (
        <>
          <h1>
            Kirish: <span>{session.user.email}</span>
          </h1>
          <h3>Nom: {session.user.name}</h3>
          <img src={session.user.image} alt={session.user.name} />
        </>
      )}
      {collectionData.map((user) => (
        <div key={user.id}>
          <h2>{user.personName}</h2>
          <p>{user.personAge}</p>
          <h3>{user.job}</h3>
          <p>{user.jobLocation}</p>
          <p>{user.student}</p>
        </div>
      ))}
    </div>
  );
}
